MB-61719: Build Faiss with or without AVX2 support
Use the cbdeps build PROFILE as the value of FAISS_OPT_LEVEL, so either
"generic" or "avx2".

On Windows, build OpenMP from source similar to Mac.

Also remove package/CMakeLists.txt - not necessary.

Also improve build-one-cbdep to make it easier to test builds locally.

Change-Id: Idb9a68dae9c42eaefddec4add916c503232c0703
Reviewed-on: https://review.couchbase.org/c/build-tools/+/214497
Reviewed-by: Rahul Rampure <rahul.rampure@couchbase.com>
Reviewed-by: Abhi Dangeti <abhinav@couchbase.com>
Tested-by: Chris Hillery <ceej@couchbase.com>

diff --git a/cbdeps/scripts/build-one-cbdep b/cbdeps/scripts/build-one-cbdep
--- a/cbdeps/scripts/build-one-cbdep
+++ b/cbdeps/scripts/build-one-cbdep
@@ -1,17 +1,39 @@
 #!/usr/bin/env bash
 
-set -ex
+set -e
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 source ${SCRIPT_DIR}/../../utilities/shell-utils.sh
 
+# This is only for interactive use; when running on Jenkins, this script
+# still expects to find all of these variables set in the environment.
+usage() {
+    echo "Usage: $0 -p PRODUCT -r RELEASE -v VERSION -b BLD_NUM -a ARCH -f PLATFORM -l PROFILE"
+    exit 1
+}
+while getopts "p:r:v:b:a:f:l:h?" opt; do
+    case $opt in
+        p) PRODUCT=$OPTARG;;
+        r) RELEASE=$OPTARG;;
+        v) VERSION=$OPTARG;;
+        b) BLD_NUM=$OPTARG;;
+        a) ARCH=$OPTARG;;
+        f) PLATFORM=$OPTARG;;
+        l) PROFILE=$OPTARG;;
+        h|?) usage;;
+        *) echo "Invalid argument $opt"
+           usage;;
+    esac
+done
+
+
 chk_set PRODUCT
-chk_set PLATFORM
-chk_set PROFILE
 chk_set RELEASE
 chk_set VERSION
 chk_set BLD_NUM
 chk_set ARCH
+chk_set PLATFORM
+chk_set PROFILE
 
 # One special-case for cross-compiling Windows; it always wants to be
 # arch "amd64". build-one-cbdep.bat enforces this, so we also do it
